### ISSUE TITLE
mem-per-gpu

### ISSUE THREAD

**Issue by Queuecumber** [facebookincubator/submitit#14]
I want to use `--mem-per-gpu` which I can set using the addtional-parameters, but since it is incompatible with the `--mem` flag, it causes sbatch to crash since `--mem` is set automatically. Can `--mem` be made optional?

**Comment by jrapin** [comment]
Hi,
I think it makes sense indeed to make it optional and add `mem_per_gpu`. I had a look at the implications it would have, in our cluster that would fallback to 60GB which is basically equivalent. I'd like @gwenzek's point of view before proceeding though (currently off the grid, so that would be for next week).

In the mean time you may be able to override `mem` using `mem=None` or `slurm_mem=None` depending on your version (although I didn't test it so not sure it will work, but worth a try)

**Comment by gwenzek** [comment]
Yes, I think this is a good idea to add `mem_per_gpu` and removing

Providing a default mem is probably not a good anyway, we should use the cluster default (which is not setting anything).

A PR would be welcome, you'd be the first external contributor :-)

But if I may ask, why is your scheduling GPU centered ? For me it makes more sense to have a task centered scheduling, and I typically have one task per gpu.

**Comment by Queuecumber** [comment]
In a sense it's both, in general I use 1 GPU per task but if I change that I'd like to make sure cores and memory goes up as well. On a related subject I'd also like to see `ntasks` supported vs setting `nodes` and `ntasks_per_node` explicitly, this way the scheduler can harvest GPUs from machines that might have 1 or 2 left over from someone elses scheduling instead of only filling full nodes.

**Comment by gwenzek** [comment]
Solved by #22
