### ISSUE TITLE
Temporary pickle path is not always removed

### ISSUE THREAD

**Issue by louismartin** [facebookincubator/submitit#1592]
https://github.com/facebookincubator/submitit/blob/f76c6635f7d7f705a5f7340461bd250f35ae08c0/submitit/core/core.py#L713
I am having problems with the temporary pickle path created at job submission. When looking at my submitit directory, there are tons of temporary pickles leftover (probably thousands). I was looking at this because submitting jobs is very on my system (submitting 45 jobs takes 50 seconds and profiling tells me that the culprits are `io.open`, `posix.mkdir` and `posix.rename`).

Two solutions I see to solve the leftover pickle paths:
- One of my guess is that they are not removed when an error happens during submission, so a simple method would be to add a try-except and remove them on error.
- A cleaner solution would be to create a temp file in the temp directory of the system `tempfile.mkstemp` instead of in the submitit dir. This way the system manages clearing the temporary storage. A small drawback is that if the temporary storage is not on the same device as the submitit dir, we will have an additional cross-device copy operation happening.

**Comment by louismartin** [comment]
Just tried the second option and it also solves my speed issue (submits 45 jobs in only 0.8s now).
I think it's because my submitit directory contains 300k jobs so creating and moving the temporary file there might be slow there ..?

**Comment by gwenzek** [comment]
> they are not removed when an error happens during submission,

I believe that's a feature because it allows you to debug what happened, you can look at the generated sbatch file or the pickle itself.

> tempfile.mkstemp

I think we may want to use the /tmp/ dir or whatever the system is configured to use as /tmp folder. But `mkstemps` is not necessarily the fastest thing because it handles data race, which we don't need because of the GUI trick. Also there is this issue of using a potentially different disks. My logs are generally on `/checkpoint` which is remote while `/tmp` is a local drive.

> submitting 45 jobs takes 50 seconds

Could you try to do the same measurement in a new log folder ? A lot of file operations become crazy slow on Linux for folders which have thousands of files.
And could you point me (by chat) to the folder you have your logs on ? I'd like to understand is the number of files in general or the number of temporary files left behind.

I don't think automatically deleting files is something we want to do, because they may include important logs/checkpoint. But I'm okay with deleting old unsubmitted pickles.

**Comment by louismartin** [comment]
I forgot to give updates on this issue.
Actually you were right on the slowness problem, it was because I had thousand of files in the same folder, and every linux command was painfully slow (even `ls` took >1min). 
I cleaned my folder and now everything is smooth again.

Concerning the unsubmitted pickle issue, maybe just using the system /tmp folder will be enough, we can still find the file after a failed run to investigate but it will be removed by the system from time to time and won't clutter the logs dir.

**Comment by gwenzek** [comment]
thanks. submitit is not doing any cleanup at all. Not sure if there is a good way of doing it automatically.
