### ISSUE TITLE
Combining results without leaving a shell running

### ISSUE THREAD

**Issue by sgbaird** [facebookincubator/submitit#1625]
Any suggestions for combining results from jobs (i.e. `job.result()`) without leaving a shell running the whole time? Just loop through the folders, load each pickle, and append the output? Or is there a better way, e.g. using job dependencies?

For example, a typical way to grab all the results (while leaving a shell running) would be:
```python
import submitit

a = [1, 2, 3, 4]
b = [10, 20, 30, 40]

executor = submitit.AutoExecutor(folder=log_folder)
executor.update_parameters(slurm_array_parallelism=2)
jobs = executor.map_array(add, a, b) # should I save jobs as a .pkl? Or is there a better way to reload these?

# what if the shell stopped here? What's a simple way to perform the next few lines (or equivalent)?
out = []
for job in jobs:
    out.append(job.result())

print(out)
# [11, 22, 33, 44]
```

**Comment by jrapin** [comment]
It really depends what you want to do, I think all options are OK. There is no parameter for job dependency for now (easy to add though), but you can always use `executor.update_parameters(slurm_additional_parameters={...})`

**Comment by gwenzek** [comment]
so generally I just prepend `screen` to long running monitoring scripts that need to live for several days.

One fancy thing I did in the past was to store on disk a mapping between the work to be done and job ids.
When relaunching I would load this mapping and try to reconnect to the job if it was still running or load the corresponding pickle otherwise. You can do all this outside of submitit, but we are open to helper functions.
