### ISSUE TITLE
How to comment a slurm variable?

### ISSUE THREAD

**Issue by aruhela** [facebookincubator/submitit#1639]
Hi All,

I observe the following error which is due to added: "#SBATCH --gpus-per-node=4" line in the generated slurm script.

Error : submitit.core.utils.FailedJobError: sbatch: error: Batch job submission failed: Invalid generic resource (gres) specification

Can developers/users of submitit guide me on where to comment/delete the above line in the slum script before it is submitted by the sbatch command? 

Thanks,
Amit Ruhela

**Comment by jrapin** [comment]
Hi,
If you do not specify `executor.update_parameters(gpus_per_node=4)` then this line should not be written.

**Comment by jrapin** [comment]
This is expected to be valid except in old versions of slurm, or on clusters with not enough gpus I guess

**Comment by jrapin** [comment]
> Well, I am using the GPUs cluster, and the system slurm doesn't need this parameter as nodes are allocated exclusively. Apart from this, I also don't want few other constraints like memory to be specified in the job script for the same reason. Can you tell the code where I can add simple python statements o delete or comment lines from the slurm script?

Hi,
Sorry for the delay, I have been on leave for the past 2 weeks.
I think the last PR on master should actually solve it, can you try installing it? (git clone, then `pip install .` from the repository). Anything unspecified will not have default values anymore. I still don't understand why you got `#SBATCH --gpus-per-node=4` without specifying it though, because this one did already need to be manually specified as far as I understand

**Comment by gokberkgul** [comment]
Hi, I also want to delete the option `--ntasks-per-node` because somehow that comment doesn't work on my SLURM cluster. Instead, I wanted to add `--ntasks` option. Here is how I changed the DINO code
Before;
```  
executor.update_parameters(
    mem_gb=40 * num_gpus_per_node,
    gpus_per_node=num_gpus_per_node,
    tasks_per_node=num_gpus_per_node,  # one task per GPU
    cpus_per_task=10,
    nodes=nodes,
    timeout_min=timeout_min,  # max is 60 * 72
    # Below are cluster dependent parameters
    slurm_partition=partition,
    slurm_signal_delay_s=120,
    **kwargs
)
```
My code;
```
executor.update_parameters(
    mem_per_cpu=4000,
    gpus_per_node=num_gpus_per_node,
    cpus_per_task=10,
    nodes=nodes,
    slurm_additional_parameters={'ntasks': num_gpus_per_node*nodes}, # one task per GPU
    timeout_min=timeout_min,  # max is 60 * 72
    # Below are cluster dependent parameters
    slurm_partition=partition,
    slurm_signal_delay_s=120,
    **kwargs
)
```

However, the job script generated still contains `tasks_per_node`
```
#!/bin/bash

# Parameters
#SBATCH --cpus-per-task=10
#SBATCH --error=/work/home/ag23peby/dino/%j_0_log.err
#SBATCH --gpus-per-node=1
#SBATCH --job-name=dino
#SBATCH --mem-per-cpu=4000
#SBATCH --nodes=4
#SBATCH --ntasks=4
#SBATCH --ntasks-per-node=1
#SBATCH --open-mode=append
#SBATCH --output=/work/home/ag23peby/dino/%j_0_log.out
#SBATCH --partition=testgpu24
#SBATCH --signal=USR1@120
#SBATCH --time=1440
#SBATCH --wckey=submitit

# command
export SUBMITIT_EXECUTOR=slurm
srun --output /work/home/ag23peby/dino/%j_%t_log.out --error /work/home/ag23peby/dino/%j_%t_log.err --unbuffered /home/ag23peby/.env/bin/python -u -m submitit.core._submit /work/home/ag23peby/dino
```
And I get the error 
`submitit.core.utils.FailedJobError: [E] sbatch: error: Batch job submission failed: Requested node configuration is not available`

If I manually delete the line `#SBATCH --ntasks-per-node=1` from the script and manually send it via `sbatch` it successfully sends to job to the cluster. So, I am pretty sure my problem is due to that parameter. How can I tell submitit to not automatically generate ` --ntasks-per-node`? I tried cloning from the repo and `pip install .` but it still generates.

**Comment by jrapin** [comment]
Looks like this one could not be made optional, can you check if #1644 works for you?

**Comment by gokberkgul** [comment]
Yes, I installed your commit and it works just fine, thank you so much!
