### ISSUE TITLE
Multi node jobs run till timeout even when done

### ISSUE THREAD

**Issue by samarth4149** [facebookincubator/submitit#1643]
Hi,

Thanks for the submitit utility, very useful for slurm.

When I use the utility for running multi-node training on slurm (say with a 6hr timeout window -- max my server allows), I see if the job is small and is done within 6 hrs, I can still see it running on slurm till it times out (using squeue). Guessing it has to do with the way submitit winds down the processes. (The job shows complete on the master processes' log including the submitit INFO message 'Job completed successfully')

**Comment by jrapin** [comment]
Hi,
What framework do you use to synchronize the nodes? do you know how the master node notifies the other ones when the job is over?
I haven't used multi-node training a lot, but I remember some conversations about killing non-master nodes once the master node finishes. But we ruled out the option because that was not how slurm would act by default.
Do you see some information in the non-master node logs? In particular if some signals were received and bypassed. The changes in how preemption is handled could maybe have caused this, I really don't know for now :s

**Comment by samarth4149** [comment]
Hi, sorry for the late response. I'm using the distributed package of pytorch. My code for the distributed job is actually quite similar to [DeIT](https://github.com/facebookresearch/deit)

In the non-master logs I just see the last message from submitit ('Job completed successfully'), with the same timestamp as the master.

**Comment by jrapin** [comment]
This message is the very last command run by submitit in the job https://github.com/facebookincubator/submitit/blob/55f53f9f3f72dc3934a9a6906b8b3c40f3fd7964/submitit/core/submission.py#L56
So the job should end right after, unless something was spawned by your function and did not quit properly, I would expect some thread or process somewhere :s do you spawn anything?

I can confirm that with the latest version, and a dummy multi-node multi-task job, the job completes and leaves as excepted, so right now I don't see other options :s

**Comment by samarth4149** [comment]
Hmm, thanks for the info. I do not spawn anything, but maybe I need to look into it if it could be something specific to the cluster I work on.
