### ISSUE TITLE
Error whilst 

### ISSUE THREAD

**Issue by mathota** [facebookincubator/submitit#1649]
Hi,

I was trying to run the example(add(a,b)) provided https://github.com/facebookincubator/submitit, my hpc cluster is throwing following error (script1)
submitit.core.utils.FailedJobError: sbatch: error: Job rejected: Please do not specify cores/CPUs/tasks for GPU jobs. 

So when I unset ntasks_per_node variable, my hpc cluster is throwing the following error (script 2)
IndexError: tuple index out of range

Can you please advice to resolve this 
[script1.txt](https://github.com/facebookincubator/submitit/files/7213658/script1.txt)
[script2.txt](https://github.com/facebookincubator/submitit/files/7213659/script2.txt)

**Comment by jrapin** [comment]
Hi
Which version are you using? if you don't specify anything, cores/cpus/tasks should not be preset in the latest version (it's been changed recently).
If you are using the latest version, can you please print the submission file corresponding to script1?

For the second option, it bugs because asking for no task is not really expected. Setting `slurm_ntasks_per_node=None` should work though, and it should also work after merging #1652
