### ISSUE TITLE
Can I use torchrun with submitit?

### ISSUE THREAD

**Issue by vasudev-sharma** [facebookincubator/submitit#1764]
I've a usecase where on a SLURM cluster, I am planning to use `torchrun` or `torch.distributed` with `submitit`
The purpose is to do distributed training using `torchrun` or `torch.distributed` with `submitit` + PyTorch Lightning 

How should I go ahead with it?

Thanks for the help in advance!!!

**Comment by crewtool** [comment]
Hey @vasudev-sharma, have you found a solution for this setup? I'm also interested in this. Any insights you could share would be greatly appreciated!

**Comment by EricLina** [comment]
+1

**Comment by baldassarreFe** [comment]
Short answer: no, `submitit` and `torchrun` should not be used together.

Torchrun is useful to launch multiple processes from the terminal. Those processes will run on the current machine, using only the local GPUs. It is possible to use torchrun for multi-node training by manually running `torchrun` on each node, but if you are in a SLURM environment that's not gonna work nicely.

SLURM jobs that want to run multiple processes in parallel within the same job need to use the SLURM command `srun`. Processes launched by `srun` will be distributed across all nodes, which is something that `torchrun` can not do.

Under the hood, submitit will prepare a sbatch script for you and submit it to SLURM. The sbatch script will use `srun` to launch multiple processes in parallel across all nodes. In this scenario, torchrun is not needed.

Regarding pytorch lightning, it should be able to recognize automatically that it's running in a SLURM environment managed by submitit and it should then do the right thing. If that's not the case, try opening an issue on pytorch lightning because their maintainers know better how the integration works.
